[
  {
    "id": 1,
    "name": "UZAIR AHMAD",
    "image": "images/uzair.png",
    "number": "18",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm offbreak",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "dob": "2001-08-22",
    "bio": "UZAIR GUJJAR IS A TOP PLAYER.",
    "stats": {
      "matches": 13,
      "runs": 282,
      "average": 25.15,
      "strikeRate": 210.5,
      "hundreds": 0,
      "fifties": 1,
      "sixes": 24,
      "wickets": 2,
      "economy": 2.25
    },
    "socialMedia": {
      "facebook": "https://www.facebook.com/profile.php?id=61576155086947"
    },
    "league": "bbl"
  },
  {
    "id": 2,
    "name": "M HASSAN",
    "image": "images/hassan.png",
    "number": "16",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "N/A",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "dob": "2004-04-12",
    "bio": "MUHAMMAD HASSAN IS A GOOD BATTER FOR YSA AND THE OPNER IN YSA AALL SESSION.",
    "stats": {
      "matches": 13,
      "runs": 187,
      "average": 35.15,
      "strikeRate": 180.2,
      "hundreds": 0,
      "fifties": 0,
      "sixes": 17,
      "wickets": 0
    },
    "socialMedia": {
      "facebook": "https://www.facebook.com/muhammad.hassan.886660"
    },
    "league": "bbl"
  },
  {
    "id": 3,
    "name": "UBAID ALI",
    "image": "images/ubaid.png",
    "number": "313",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "ALL-ROUNDER",
    "battingStyle": "right-hand bat",
    "bowlingStyle": "Slow right-arm fast",
    "isFeatured": true,
    "isCaptain": true,
    "isViceCaptain": false,
    "dob": "2000-07-17",
    "bio": "UBAID ALI IS CAPTAIN IN BPL SEASON 3",
    "stats": {
      "matches": 10,
      "runs": 103,
      "average": 10.01,
      "strikeRate": 95.0,
      "hundreds": 0,
      "fifties": 0,
      "sixes": 13,
      "wickets": 0
    },
    "socialMedia": {
      "facebook": "https://www.facebook.com/bydly.177138"
    },
    "league": "bbl"
  },
  {
    "id": 4,
    "name": "M MUHAVIAH",
    "image": "images/muhaviah.png",
    "number": "97",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BOWLER",
    "battingStyle": "right-hand bat",
    "bowlingStyle": "right-arm fast",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "dob": "2006-06-17",
    "bio": "MUHAVIAH IS A GOOD SPEED GUN BOWLER IN ALL SEASON FOR YSA.",
    "stats": {
      "matches": 10,
      "runs": 0,
      "wickets": 14,
      "average": 4.17,
      "economy": 7.80,
      "strikeRate": 18.2,
      "fiveWickets": 1,
      "sixes": 0
    },
    "league": "bbl"
  },
  {
    "id": 5,
    "name": "ZAID PATTNI",
    "image": "images/zahid.png",
    "number": "14",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BOWLER",
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm fast",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "dob": "2001-07-09",
    "bio": "ZAID PATTNI IS SECOND TOP BOWLER FOR YSA",
    "stats": {
      "matches": 5,
      "runs": 0,
      "wickets": 9,
      "average": 25.00,
      "economy": 2.20,
      "strikeRate": 0.0,
      "fiveWickets": 0,
      "sixes": 0
    },
    "SocialMedia": {
      "facebook": "https://www.facebook.com/m.swm.gjr.2025"
    },
    "league": "bbl"
  },
  {
    "id": 6,
    "name": "RASHID GUJJAR",
    "image": "images/rashid.png",
    "number": "69",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "ALL-ROUNDER",
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm fast",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "dob": "2004-12-15",
    "bio": "RASHID GUJJAR IS SECOND BEST ALL-ROUNDER FOR YSA.",
    "stats": {
      "matches": 8,
      "runs": 38,
      "average": 38.00,
      "strikeRate": 200.0,
      "fifties": 0,
      "sixes": 1,
      "wickets": 2,
      "bowlingAverage": 23.00,
      "economy": 1.24
    },
    "socialMedia": {
      "facebook": "https://www.facebook.com/rashidkhanvbh"
    },
    "league": "bbl"
  },
  {
    "id": 7,
    "name": "ABRAR AHMAD",
    "image": "images/abrar.png",
    "number": "56",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "battingStyle": "Right-hand bat",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": true,
    "dob": "2002-03-18",
    "bio": "ABRAR AHMAD IS VOICE CAPTAIN IN BPL SESION 3 FOR YSA",
    "stats": {
      "matches": 10,
      "runs": 2,
      "average": 2.00,
      "strikeRate": 115.0,
      "fifties": 0,
      "sixes": 0,
      "wickets": 0,
      "economy": 0.00
    },
    "league": "bbl"
  },
  {
    "id": 8,
    "name": "M IBRAHIM",
    "image": "images/Ibrahim.png",
    "number": "10",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "ALL-ROUNDER",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 4,
      "economy": 4.05,
      "matches": 0,
      "average": 0,
      "strikeRate": 0,
      "bowlingAverage": 0
    },
    "bio": "TBD.",
    "league": "bbl"
  },
  {
    "id": 9,
    "name": "M AZAM",
    "image": "images/azam.png",
    "number": "39",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0
    },
    "bio": "TBD.",
    "league": "bbl"
  },
  {
    "id": 10,
    "name": "TARIQ GUJJAR",
    "image": "images/tariq.png",
    "number": "50",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0
    },
    "bio": "TBD",
    "league": "bbl"
  },
  {
    "id": 11,
    "name": "SHAHID KHAN",
    "image": "images/shahid.png",
    "number": "05",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0
    },
    "bio": "TBD",
    "league": "bbl"
  },
  {
    "id": 12,
    "name": "UBAID ULLAH",
    "image": "images/ubaidullah.png",
    "number": "45",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BATTER",
    "isFeatured": true,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0
    },
    "bio": "TBD",
    "league": "bbl"
  },
  {
    "id": 13,
    "name": "M HASSAN (ALL-ROUNDER)",
    "image": "images/hassan1.png",
    "number": "66",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "ALL-ROUNDER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0,
      "bowlingAverage": 0,
      "economy": 0
    },
    "bio": "TBD.",
    "league": "bbl"
  },
  {
    "id": 14,
    "name": "M HUSSAIN",
    "image": "images/hussain.png",
    "number": "67",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "BOWLER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "economy": 0,
      "strikeRate": 0,
      "fiveWickets": 0
    },
    "bio": "TBD",
    "league": "bbl"
  },
  {
    "id": 15,
    "name": "NAWAZ GUJJAR",
    "image": "images/nawaz.png",
    "number": "99",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰🇵🇸",
    "role": "ALL-ROUNDER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0,
      "bowlingAverage": 0,
      "economy": 0
    },
    "bio": "TBD.",
    "league": "bbl"
  },
  {
    "id": 16,
    "name": "JAWAD AHMAD",
    "image": "images/jawad.png",
    "number": "96",
    "country": "PAKISTAN",
    "countryFlag": "🇵🇰",
    "role": "BATTER",
    "isFeatured": false,
    "isCaptain": false,
    "isViceCaptain": false,
    "stats": {
      "runs": 0,
      "sixes": 0,
      "wickets": 0,
      "matches": 0,
      "average": 0,
      "strikeRate": 0
    },
    "bio": "TBD.",
    "league": "bbl"
  }
]